<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>IIIF.Manifests.Serializer</RootNamespace>
        <PackageId>IIIF.Manifest.Serializer.Net</PackageId>
        <Title>IIIF Manifest Serializer .NET</Title>
        <PackageTags>iiif;manifest;presentation-api;serializer;json;newtonsoft-json</PackageTags>
        <Authors>Kiarash Minoo, IIIF Manifest Serializer</Authors>
        <RepositoryUrl>https://github.com/KiarashMinoo/IIIF.Manifest.Serializer.Net</RepositoryUrl>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json"/>
        <PackageReference Include="System.Text.Json"/>
    </ItemGroup>
    <ItemGroup>
        <Compile Update="Shared\Trackable\TrackableObject.Getters.cs">
            <DependentUpon>TrackableObject.cs</DependentUpon>
        </Compile>
        <Compile Update="Shared\Trackable\TrackableObject.Setters.cs">
            <DependentUpon>TrackableObject.cs</DependentUpon>
        </Compile>
        <Compile Update="Shared\Trackable\TrackableObject.AdditionalPropertiesHandler.cs">
            <DependentUpon>TrackableObject.cs</DependentUpon>
        </Compile>
        <Compile Update="Shared\Trackable\TrackableObjectPropertyChangedEventArgs.cs">
          <DependentUpon>TrackableObjectPropertyChangedEventHandler.cs</DependentUpon>
        </Compile>
        <Compile Update="Shared\Trackable\TrackableObjectPropertyChangingEventArgs.cs">
          <DependentUpon>TrackableObjectPropertyChangingEventHandler.cs</DependentUpon>
        </Compile>
        <Compile Update="Shared\Trackable\TrackableObject.ChangeTracking.cs">
          <DependentUpon>TrackableObject.cs</DependentUpon>
        </Compile>
        <Compile Update="Shared\Trackable\TrackableCollectionChangedEventArgs.cs">
          <DependentUpon>TrackableCollectionChangedEventHandler.cs</DependentUpon>
        </Compile>
        <Compile Update="Shared\Trackable\TrackableCollectionChangingEventArgs.cs">
          <DependentUpon>TrackableCollectionChangingEventHandler.cs</DependentUpon>
        </Compile>
        <Compile Update="Shared\Trackable\CollectionChangedType.cs">
          <DependentUpon>TrackableCollection.cs</DependentUpon>
        </Compile>
    </ItemGroup>
</Project>
