name: PR-Agent AI Code Review

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: read
  pull-requests: write
  issues: write

concurrency:
  group: pr-agent-wrapper-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pr-agent:
    if: github.event.pull_request.draft == false
    uses: KiarashMinoo/.github/.github/workflows/reusable-pr-agent.yml@main

    secrets:
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
